### ISSUE TITLE
NoMethodError (undefined method `values_at' for nil:NilClass)

### ISSUE THREAD

**Issue by bugdimes** [koshilife/calendly-api-ruby-client#50]
Hi @koshilife 
I have setup a client object by passing my "personal access token" to the class using
`client = Calendly::Client.new token`

when I perform `client.me` It returns below error

By the way, Thanks for making such client 

By the way
My Ruby version: 2.7.5
Faraday: 0.15.4

```D, [2022-06-28T20:57:09.887126 #53164] DEBUG -- : Request GET https://api.calendly.com/users/me params:, body:
WARNING: No adapter was configured for this request
Traceback (most recent call last):
        1: from (irb):13
NoMethodError (undefined method `values_at' for nil:NilClass)

**Comment by koshilife** [comment]
@bugdimes thanks for reaching out.

It might be caused by your faraday version which was old.
When I used the same version of faraday (0.15.4), I could reproduce it.
Also, I could confirm that it worked using Faraday 1.0.0 and 2.3.0.

I will think about improving the definition of dependencies.

**Comment by bugdimes** [comment]
Thanks @koshilife for the quick response
Yes, upgrading my Faraday version solved the issue, 
Thanks, 
Also, I want to contribute to this project, Please let me know If there is any way. Thakns

**Comment by koshilife** [comment]
> Also, I want to contribute to this project, Please let me know If there is any way. Thanks

Thank you for your kind consideration and also for sending an email.
Now, The information about this repo is only this GitHub repo and an auto-generated [rubydoc.info](https://www.rubydoc.info/gems/calendly/).

If you have good ideas for improving or confusing things, you can open issues and PRs anytime. You are very welcome.
